[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    knolleary/PubSubClient
    bblanchon/ArduinoJson@^7.0.0
    zinggjm/GxEPD2@^1.6.4
    adafruit/Adafruit GFX Library
    olikraus/U8g2_for_Adafruit_GFX
    olikraus/U8g2
monitor_speed = 115200
board_build.partitions = huge_app.csv